fix: add imageBuilds config to values-hub.yaml to enable BuildConfigs
Root cause: BuildConfigs weren't being created because:
1. imageBuilds.gitRepository was empty/placeholder
2. Template checks: {{- if $gitUrl }} before rendering

Error: ImagePullBackOff on pods (images don't exist)

Solution: Added imageBuilds section to values-hub.yaml with:
- enabled: true
- gitRepository: tosin2013/openshift-aiops-platform
- gitRef: main
- gitCredentialsSecret: git-credentials-source

This will create:
- ImageStreams: coordination-engine, notebook-validator
- BuildConfigs: coordination-engine, notebook-validator
- Images will be built from src/ directories

Signed-off-by: Tosin Akinosho <takinosh@redhat.com>