fix: add subscriptions section to values-hub.yaml for clustergroup chart
Error: template: clustergroup/templates/core/operatorgroup.yaml:15:22:
  executing at <.disabled>: can't evaluate field disabled

Root cause: clustergroup chart expects subscriptions section even if empty

Solution: Added subscriptions: {} to satisfy chart requirements
Signed-off-by: Tosin Akinosho <takinosh@redhat.com>